site_name: Grasshopper

repo_name: "2022.2-Grasshopper"
repo_url: "https://github.com/Requisitos-de-Software/2022.2-Grasshopper"

theme:
  name: material
  language: "pt"
  logo: assets/grasshopper.svg
  favicon: assets/fav.png
  palette:
    primary: indigo
    accent: light green
  features:
    - navigation.tabs

nav:
  - Inicio: index.md
  - Planejamento:
      - Reuniões: planejamento/reunioes.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Aplicativos analisados: planejamento/aplicativos-analisados.md
  - Pré-rastreabilidade:
      - Rich picture: pre-traceability/richpicture.md
  - Elicitação:
      - Perfil do usuário: elicitacao/perfil-do-usuario.md
      - Personas: elicitacao/personas.md
      - Storytelling: elicitacao/storytelling.md
      - Brainstorm: elicitacao/brainstorm.md
      - Observação: elicitacao/observacao.md
      - Priorização:
          - In or Out: elicitacao/priorizacao/in-or-out.md
          - Three Level-Scale: elicitacao/priorizacao/threeLevel-Scale.md
  - Modelagem:
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Casos de Uso: modelagem/casos-de-uso.md
      - Especifição Suplementar: modelagem/especificao-suplementar.md
      - Ágil:
        - Histórias de Usuário: modelagem/modelagemAgil/historias-de-usuario.md
  - Análise de Requisitos:
      - Verificação:
          - Modelo Padrão: analise-de-requisitos/verificacao/modelo-padrao.md
          - Teste Piloto - Lichess:
            - Rich Picture: analise-de-requisitos/verificacao/testePiloto-Lichess/richpicture-Lichess.md
            - Personas: analise-de-requisitos/verificacao/testePiloto-Lichess/personas-Lichess.md
  - Atas das Reuniões:
      - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 17/11/2022: atas-das-reunioes/reuniao2.md
      - Reunião 3 - 22/11/2022: atas-das-reunioes/reuniao3.md
      - Reunião 4 - 01/12/2022: atas-das-reunioes/reuniao4.md
  - Apresentações:
      - Etapa 1 - 21/11: apresentacoes/etapa1.md
      - Etapa 2 - 30/11: apresentacoes/etapa2.md
      - Etapa 3 - 12/12: apresentacoes/etapa3.md
