site_name: Grasshopper

repo_name: "2022.2-Grasshopper"
repo_url: "https://github.com/Requisitos-de-Software/2022.2-Grasshopper"

theme:
  name: material
  logo: assets/grasshopper.svg
  favicon: assets/fav.png
  palette:
    primary: indigo
    accent: light green
  features:
    - navigation.tabs

nav:
  - Inicio: index.md
  - Planejamento:
      - Reuniões: planejamento/reunioes.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Cronograma: planejamento/cronograma.md
      - Aplicativos analisados: planejamento/aplicativos-analisados.md
  - Pré-rastreabilidade:
      - Rich picture: pre-traceability/richpicture.md
  - Atas das Reuniões:
    - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
    - Reunião 2 - 17/11/2022: atas-das-reunioes/reuniao2.md
